CREATE TABLE `sap_physical_inventory_document_item_data`
(
  `FiscalYear`                       varchar(4) NOT NULL,
  `PhysicalInventoryDocument`        varchar(10) NOT NULL,
  `PhysicalInventoryDocumentItem`    varchar(3) NOT NULL,
  `Plant`                            varchar(4) DEFAULT NULL,
  `StorageLocation`                  varchar(4) DEFAULT NULL,
  `InventorySpecialStockType`        varchar(1) DEFAULT NULL,
  `Material`                         varchar(40) DEFAULT NULL,
  `Batch`                            varchar(10) DEFAULT NULL,
  `PhysicalInventoryStockType`       varchar(1) DEFAULT NULL,
  `SalesOrder`                       varchar(10) DEFAULT NULL,
  `SalesOrderItem`                   varchar(6) DEFAULT NULL,
  `Supplier`                         varchar(10) DEFAULT NULL,
  `Customer`                         varchar(10) DEFAULT NULL,
  `WBSElement`                       varchar(24) DEFAULT NULL,
  `LastChangeDate`                   varchar(80) DEFAULT NULL,
  `CountedByUser`                    varchar(12) DEFAULT NULL,
  `PhysicalInventoryLastCountDate`   varchar(80) DEFAULT NULL,
  `AdjustmentPostingMadeByUser`      varchar(12) DEFAULT NULL,
  `PostingDate`                      varchar(80) DEFAULT NULL,
  `PhysicalInventoryItemIsCounted`   tinyint(1) DEFAULT NULL,
  `PhysInvtryDifferenceIsPosted`     tinyint(1) DEFAULT NULL,
  `PhysInvtryItemIsRecounted`        tinyint(1) DEFAULT NULL,
  `PhysInvtryItemIsDeleted`          tinyint(1) DEFAULT NULL,
  `IsHandledInAltvUnitOfMsr`         tinyint(1) DEFAULT NULL,
  `CycleCountType`                   varchar(1) DEFAULT NULL,
  `IsValueOnlyMaterial`              tinyint(1) DEFAULT NULL,
  `PhysInventoryReferenceNumber`     varchar(16) DEFAULT NULL,
  `MaterialDocument`                 varchar(10) DEFAULT NULL,
  `MaterialDocumentYear`             varchar(4) DEFAULT NULL,
  `MaterialDocumentItem`             varchar(4) DEFAULT NULL,
  `PhysInvtryRecountDocument`        varchar(10) DEFAULT NULL,
  `PhysicalInventoryItemIsZero`      tinyint(1) DEFAULT NULL,
  `ReasonForPhysInvtryDifference`    varchar(4) DEFAULT NULL,
  `MaterialBaseUnit`                 varchar(3) DEFAULT NULL,
  `BookQtyBfrCountInMatlBaseUnit`    varchar(15) DEFAULT NULL,
  `Quantity`                         varchar(15) DEFAULT NULL,
  `UnitOfEntry`                      varchar(3) DEFAULT NULL,
  `QuantityInUnitOfEntry`            varchar(15) DEFAULT NULL,
  `Currency`                         varchar(5) DEFAULT NULL,
  `LastChangeDateTime`               varchar(80) DEFAULT NULL,
    PRIMARY KEY (`FiscalYear`, `PhysicalInventoryDocument`, `PhysicalInventoryDocumentItem`),
    CONSTRAINT `SAPPhysicalInventoryDocumentItemData_fk` FOREIGN KEY (`FiscalYear`, `PhysicalInventoryDocument`) REFERENCES `sap_physical_inventory_document_header_data` (`FiscalYear`, `PhysicalInventoryDocument`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
